# **Analyse London Olympics Dataset**
DESCRIPTION

Problem: 

Evaluate the dataset of the Summer Olympics, London 2012 to:

    Find and print the name of the country that won maximum gold medals,
    Find and print the countries who won more than 20 gold medals,
    Print the medal tally,
    Print each country name with the corresponding number of gold medals, and
    Print each country's name with the total number of medals won.


**Dataset link**<br>
https://docs.google.com/spreadsheets/d/1m4aUxe5As68cgwgO-XhdfahvuR89BcgR/edit?usp=sharing&ouid=101253720317841050313&rtpof=true&sd=true

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#read the dataset
dataset=pd.read_excel('/content/Olympic 2012 Medal Tally.xlsx')
dataset

Unnamed: 0     Unnamed: 1    Unnamed: 2 Unnamed: 3   Unnamed: 4 Unnamed: 5  \
0         NaN        Country  Country Code       Year  Medal Tally        NaN   
1         NaN            NaN           NaN        NaN         Gold     Silver   
2         NaN  Great Britain           GBR       2012           29         17   
3         NaN         China            CHN       2012           38         28   
4         NaN         Russia           RUS       2012           24         25   
5         NaN  United States            US       2012           46         28   
6         NaN          Korea           KOR       2012           13          8   
7         NaN          Japan           JPN       2012            7         14   
8         NaN        Germany           GER       2012           11         11   

  Unnamed: 6  
0        NaN  
1     Bronze  
2         19  
3         22  
4         32  
5         29  
6          7  
7         17  
8         14

In [ ]:
#remove the first column
dataset0=dataset.iloc[2:,1:]
print(dataset0)

      Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6
2  Great Britain        GBR       2012         29         17         19
3         China         CHN       2012         38         28         22
4         Russia        RUS       2012         24         25         32
5  United States         US       2012         46         28         29
6          Korea        KOR       2012         13          8          7
7          Japan        JPN       2012          7         14         17
8        Germany        GER       2012         11         11         14


In [ ]:
dataset00=dataset0.iloc[:,:3]
#rename the column name
dataset00.rename(columns = {'Unnamed: 1':'Country','Unnamed: 2':'Country Code','Unnamed: 3':'Year'}, inplace = True)
dataset00.rename(columns = {'Country':'Country','\tCountry Code':'Country Code','\tYear':'Year'}, inplace = True)
dataset00

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Country Country Code  Year
2  Great Britain          GBR  2012
3         China           CHN  2012
4         Russia          RUS  2012
5  United States           US  2012
6          Korea          KOR  2012
7          Japan          JPN  2012
8        Germany          GER  2012

In [ ]:
dataset1=dataset0.iloc[:,3:]
#rename the column name
dataset1.rename(columns = {'Unnamed: 4':'Gold','Unnamed: 5':'Silver','Unnamed: 6':'Bronze'}, inplace = True)
# dataset1.rename(columns = {'Country':'Country','\tCountry Code':'Country Code','\tYear':'Year'}, inplace = True)
dataset1

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Gold Silver Bronze
2   29     17     19
3   38     28     22
4   24     25     32
5   46     28     29
6   13      8      7
7    7     14     17
8   11     11     14

**Find and print the name of the country that won maximum gold medals**

In [ ]:
gold_array=np.array(dataset1['Gold'])
print(gold_array)
silver_array=np.array(dataset1['Silver'])
print(silver_array)
bronze_array=np.array(dataset1['Bronze'])
print(bronze_array)
country_array=np.array(dataset00['Country'])
print(country_array)

[29 38 24 46 13 7 11]
[17 28 25 28 8 14 11]
[19 22 32 29 7 17 14]
['Great Britain' 'China ' 'Russia' 'United States' 'Korea' 'Japan'
 'Germany']


In [ ]:
gold_array=np.array(gold_array)
gold_array_max=gold_array.argmax()
print(gold_array_max)
country_array_max=country_array[gold_array_max]
country_array_max

3


'United States'

**Find and print the countries who won more than 20 gold medals**

In [ ]:
gold_array=np.array(gold_array)
gold_array_max_con=gold_array > 20
# print(gold_array_max_con)
country_array_max_con=country_array[gold_array_max_con]
country_array_max_con

array(['Great Britain', 'China ', 'Russia', 'United States'], dtype=object)

**Print the medal tally**

In [ ]:
#Print each country name with the corresponding number of gold medals, and
#Print each country's name with the total number of medals won.
# gold_array
# country_array
countrys=['Great Britain','China''Russia','United States','Korea','Japan','Germany']
print(countrys)
silver_array=np.array(dataset1['Silver'])
print(silver_array)
bronze_array=np.array(dataset1['Bronze'])
print(bronze_array)

['Great Britain', 'ChinaRussia', 'United States', 'Korea', 'Japan', 'Germany']
[17 28 25 28 8 14 11]
[19 22 32 29 7 17 14]


In [ ]:
for i in range(len(countrys)):
  total_medals=silver_array[i]+bronze_array[i]+gold_array[i]
  print('Evaluate the country Name', countrys[i] , 'with the corresponding number of gold medals is',gold_array[i],'Total Medals=', total_medals)

Evaluate the country Name Great Britain with the corresponding number of gold medals is 29 Total Medals= 65
Evaluate the country Name ChinaRussia with the corresponding number of gold medals is 38 Total Medals= 88
Evaluate the country Name United States with the corresponding number of gold medals is 24 Total Medals= 81
Evaluate the country Name Korea with the corresponding number of gold medals is 46 Total Medals= 103
Evaluate the country Name Japan with the corresponding number of gold medals is 13 Total Medals= 28
Evaluate the country Name Germany with the corresponding number of gold medals is 7 Total Medals= 38
